version: '3.8'
services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - stats_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d stats -U postgres" ]
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ewm_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ewm -U postgres" ]
      timeout: 5s
      interval: 5s
      retries: 10

  stats-server:
    build:
      context: ./stats-service-parent/stats-service
      dockerfile: Dockerfile
    container_name: stats-server
    depends_on:
      - stats-db
    environment:
      SERVER_PORT: 9090
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: stats-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: stats
    ports:
      - "9090:9090"

  ewm-service:
    build:
      context: ./main-service
      dockerfile: Dockerfile
    container_name: ewm-service
    depends_on:
      ewm-db:
        condition: service_healthy
      stats-server:
        condition: service_started
    environment:
      SERVER_PORT: 8080
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: ewm-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ewm
      STATS_SERVICE_URL: http://stats-server:9090
    ports:
      - "8080:8080"

volumes:
  stats_pgdata:
  ewm_pgdata:
