CREATE SEQUENCE IF NOT EXISTS ENDPOINT_HIT_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS endpoint_hit
(
    id        BIGINT DEFAULT NEXTVAL('ENDPOINT_HIT_ID_SEQ') PRIMARY KEY,
    app       TEXT    NOT NULL,
    uri       TEXT    NOT NULL,
    ip        TEXT    NOT NULL,
    timestamp TIMESTAMP NOT NULL
);
